### DISCUSSION TITLE
Any faster way to iteratively develop with docker install of Szurubooru?

### DISCUSSION THREAD

**Discussion by sticknuder** [rr-/szurubooru#628] [Q&A]
My current workflow is to change files then run `sudo DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build --no-cache` because as the install instructions mentioned, and I have experienced once, when building with cache sometimes changes don't take effect.

The problem is that is takes a really long time to build on my pi. I was wondering if there's a better workflow for modifying the source and building the docker containers that both ensures all changes take effect and is faster.

Thanks in advance

**Comment by BloodyRain2k** [comment]
For the client it might not be impossible to get around rebuilding, because the JS needs to be "compiled" to work.

For the server it's possible to copy the source and map it to the docker's copy that it would use normally.
That way I can override what's inside the image with my in-dev version and only have to restart the docker to apply the changes.
But I'm just running `docker-compose up` in the project root, so I don't know how that would need to be adapted to work on the Pi.
Anyways, here's what my docker-compose file looks like for the server:
```
  server:
    container_name: sz_server
    # image: szurubooru/server:latest
    build: server
    depends_on:
      - sql
    environment:
      POSTGRES_HOST: sql
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      THREADS:
    volumes:
      - "${MOUNT_DATA}:/data"
      - "./server/config.yaml:/opt/app/config.yaml"
      - "./server/szurubooru:/opt/app/szurubooru"
    ports:
      - "56789:5678"
```
