### ISSUE TITLE
Accessing the service via subdomain

### ISSUE THREAD

**Issue by frumpymoons** [rr-/szurubooru#318]
Hello, I deploy all my services with different subdomains. 
Like: 
**service1**.example.com
**service2**.example.com

Is it possible to set this up instead of a different path/base url?

My docker-compose.yml
```
  szuru-server:
    image: szurubooru/server:latest
    container_name: szuru-server
    depends_on:
      - szuru-db
    environment:
      POSTGRES_HOST: szuru-db
      POSTGRES_USER: ***
      POSTGRES_PASSWORD: ***
    volumes:
      - /opt/docker/szuru/data:/data
      - /opt/docker/szuru/config.yaml:/opt/app/config.yaml

  szuru-client:
    image: szurubooru/client:latest
    container_name: szuru-client
    depends_on:
      - szuru-server
    environment:
      BACKEND_HOST: szuru-server
      PORT: 127.0.0.1:80
    volumes:
      - /opt/docker/szuru/data:/data:ro
    ports:
      - 1337:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.szuru.entrypoints=web,web-secure
      - traefik.http.routers.szuru.rule=Host(`szuru.***.xyz`)
      - traefik.http.routers.szuru.tls.domains[0].main=***.xyz
      - traefik.http.routers.szuru.tls.domains[0].sans=*.***.xyz
      - traefik.http.services.szuru.loadbalancer.server.port=80
      - traefik.http.services.szuru.loadbalancer.server.scheme=http

  szuru-db:
    image: postgres:11-alpine
    container_name: szuru-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ***
      POSTGRES_PASSWORD: ***
    volumes:
      - /opt/docker/postgres:/var/lib/postgresql/data
```
