### ISSUE TITLE
Post Flow doesn't handle statistics well.

### ISSUE THREAD

**Issue by kaijuagenda** [rr-/szurubooru#353]
The feature implemented from Issue #351 can produce some visual errors for post statics, overlayed on thumbnails that have a vertical aspect ratio, and more than two statistic types.

![Screenshot_2020-10-01 Anthro cc BETA – Listing posts](https://user-images.githubusercontent.com/52358618/94871134-4bf46980-0417-11eb-9ba5-95a938ced6f5.png)

**Comment by Dreomite** [comment]
Now I understand why there was `min-width` set.

I'm not quite sure how to deal with this, since I don't have project vision. I don't know what can be changed and what can't. And I would change quite a lot.

The problem with `min-width` is that it will either cut thumbnails too aggressively or, if proper post flow is implemented, there won't be more than 2 images per line on a typical mobile screen. You can browse DA on your phone to see what I'm talking about. Would it be inconvenient for a booru?


I played with CSS a bit and came up with this dirty solution which I don't particularly like. Just throwing ideas around.

Before:
![image](https://user-images.githubusercontent.com/35058624/95267464-003e2780-083e-11eb-97d5-666496221a0e.png)

After:
![image](https://user-images.githubusercontent.com/35058624/95267427-e69ce000-083d-11eb-86b6-7e86bbdb0be4.png)

Firefox inspector CSS "diff":
```css

/* app.min.css */

.post-list ul li .thumbnail-wrapper .stats, .post-list ul li .thumbnail-wrapper .type {
  /* padding: .33em .5em; */
  /* background: rgba(0,0,0,.5); */
  /* height: 1em; */
}

.post-list ul li .thumbnail-wrapper .stats .icon:not(:first-of-type) {
  /* margin-left: 1em; */
}

.post-list ul li .thumbnail-wrapper .stats {
  display: inline-flex;
  flex-wrap: wrap-reverse;
  justify-content: flex-end;
}

.post-list ul li .thumbnail-wrapper {
  /* line-height: 80%; */
}

/* Inline #5 */

.icon {
  background: rgba(0,0,0,.5);
  padding: .1em .5em;
  min-width: 2.1em;
}
```
