### ISSUE TITLE
Unsuccessful HTTP response

### ISSUE THREAD

**Issue by lincolnthedev** [rr-/szurubooru#407]
When uploading an image, I get the message "Unsuccessful HTTP response"

**Comment by neobooru** [comment]
Did you install using the docker method, or did you manually install all the parts?
If you used docker then please post the output of `docker-compose logs`, if you manually installed then please show the server output.
I assume that it has to do with incorrect permissions on the data folder, but I can't know for sure without the logs.

**Comment by lincolnthedev** [comment]
I tried to set permissions with `sudo chown -R 1000:1000 /var/local/szurubooru` and followed #319, but still doesn't seem to be working. Logs are attached.

[_szuru_server_1_logs.txt](https://github.com/rr-/szurubooru/files/6511263/_szuru_server_1_logs.txt)

**Comment by lincolnthedev** [comment]
Also, it seems the thumbnails are now messed up as well.

<img width="1440" alt="Screen Shot 2021-05-19 at 4 00 47 PM" src="https://user-images.githubusercontent.com/41193328/118876552-62263b80-b8bb-11eb-8b3a-0fc8d3801a46.png">

**Comment by neobooru** [comment]
How did you manage to upload those images? Was this after you changed the `/var/local/szurubooru` folder permissions?
Is the error in the server logs the same error as you have been getting before (when you couldn't upload posts), or is this a new error? It looks like it is an postgresql error, in which case we'd need to see the postgresql logs too.

**Comment by lincolnthedev** [comment]
Yes, I did add the PUID and PGID environment variables.

Digging around in the logs, I found this:
`172.20.0.5 -> GET /data/generated-thumbnails/2_0fbdab98281fbdf1.jpg HTTP/1.1 [404] - referer: https://<SERVER DOMAIN>/posts <MY IP>


2021/05/19 20:44:47 [error] 12#12: *850 open() "/data/generated-thumbnails/1_269a2457a36c6314.jpg" failed (2: No such file or directory), client: 172.20.0.5, server: , request: "GET /data/generated-thumbnails/1_269a2457a36c6314.jpg HTTP/1.1", host: "<SERVER DOMAIN>", referrer: "https://<SERVER DOMAIN>/posts"`

**Comment by lincolnthedev** [comment]
I uploaded the images with Imgur links

**Comment by neobooru** [comment]
It looks like the postgresql also doesn't have permission to write to it's path (`MOUNT_SQL` in .env, which defaults to `/var/local/szurubooru/sql`). You'll have to give your docker user permission to write to that folder, if you used PUID and PGID then you'll have to give that user write permissions to the `MOUNT_SQL` folder.
This should fix your postgresql issues, once those are fixed we can take a look at the server errors (if any).

**Comment by lincolnthedev** [comment]
Ran `sudo chown -R 1000:1000 /var/local/szurubooru/sql` and the resulting logs:
[_szuru_sql_1_logs (2).txt](https://github.com/rr-/szurubooru/files/6511595/_szuru_sql_1_logs.2.txt)

**Comment by neobooru** [comment]
Well that didn't improve the situation :S
Did you also add the `user: "1100:1100"` line (with different numbers in your case) as mentioned here -> https://github.com/rr-/szurubooru/issues/319#issuecomment-617802048
Sorry that I can't give you your answer in one go, I personally run my docker daemon as root so I don't have these issues.

**Comment by lincolnthedev** [comment]
Yes, I added that to my server container. Should I add it to my Postgres container as well?

**Comment by neobooru** [comment]
Yes, please try that. As far as I can tell you only need to set PUID and PGID for the `server` service. You'll need to add the `user: "1100:1100"` (make sure to change it to match your id) line to all services, including server. (Maybe not for `client`, but it can't hurt I guess).

**Comment by lincolnthedev** [comment]
OK, good news! The images now persist after a restart. Still not able to upload images though (except with an Imgur link.)

**Comment by neobooru** [comment]
Are your thumbnails also working again? Uploading images is handled in the `client` service (aka nginx). I previously said that you probably don't need to add the `user:...` line there, but I believe that was incorrect. Please try adding the `user:...` line to your docker-compose.yml in the `client` section. If that doesn't work then please do share the client logs.

**Comment by lincolnthedev** [comment]
New error, other than that seems good:
```
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2


2021/05/20 01:33:35 [emerg] 7#7: host not found in upstream "__BACKEND__:6666" in /etc/nginx/nginx.conf:23


nginx: [emerg] host not found in upstream "__BACKEND__:6666" in /etc/nginx/nginx.conf:23


sed: can't create temp file '/etc/nginx/nginx.confXXXXXX': Permission denied


sed: can't create temp file '/var/www/index.htmXXXXXX': Permission denied
```

**Comment by neobooru** [comment]
Just to make sure, but you docker daemon is not running as the root user right?

**Comment by lincolnthedev** [comment]
I don't believe so

**Comment by neobooru** [comment]
Alright, so I tried it for myself and this `docker-compose.yml` configuration seems to do the trick for me.

```
## Example Docker Compose configuration
##
## Use this as a template to set up docker-compose, or as guide to set up other
## orchestration services
version: '2'

services:

  server:
    image: szurubooru/server:latest
    depends_on:
      - sql
    environment:
      ## These should be the names of the dependent containers listed below,
      ## or FQDNs/IP addresses if these services are running outside of Docker
      POSTGRES_HOST: sql
      ## Credentials for database:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PUID: 1001
      PGID: 1001
      ## Commented Values are Default:
      #POSTGRES_DB: defaults to same as POSTGRES_USER
      #POSTGRES_PORT: 5432
      #LOG_SQL: 0 (1 for verbose SQL logs)
    volumes:
      - "${MOUNT_DATA}:/data"
      - "./server/config.yaml:/opt/app/config.yaml"
    user: "1001:1001"

  client:
    image: szurubooru/client:latest
    depends_on:
      - server
    environment:
      BACKEND_HOST: server
      BASE_URL:
    volumes:
      - "${MOUNT_DATA}:/data:ro"
    ports:
      - "${PORT}:80"

  sql:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - "${MOUNT_SQL}:/var/lib/postgresql/data"
    user: "1001:1001"
```

We shouldn't touch the permissions of the `client` service, because that seems to break stuff. In my case the docker daemon is running as root. The `MOUNT_DATA` and `MOUNT_SQL` (inside `.env`) folders need to be read/writable for whatever user you specified in the `user: ...` key. Usually this means that they are owned by that user.
The `MOUNT_DATA` also needs to be readable by the client user (which I believe is the same user as what the docker daemon is running), if you get problems there you could `chmod -R 644` that folder.
