### ISSUE TITLE
Can't access API in Docker deployment

### ISSUE THREAD

**Issue by BobHassok** [rr-/szurubooru#448]
I'm trying to use Grabber's upload script, but I can't find any mention of Szuru's api port. I've tested 80 and 8080 and 6666 and had no luck. I've worked with the dev of Grabber to confirm my grabber setup is working. The posts just don't show up in Szurubooru.

**Comment by neobooru** [comment]
By default the api will be accessible from `example.com/api`. You can test this in your browser as well. If you go to that url (obviously fill in your own host name) it should show an error with `This API only supports JSON responses.`.

Alternatively, if you want to use the port 6666 (which shouldn't be needed because you can use `/api`).
The docker-compose by default does not expose the port 6666. You can expose this port by changing your docker-compose.yml to look like this:
```yml
services:
  server:
    # Other stuff that you should ignore.
    # Add this section to the bottom, underneath the volumes section
    ports:
      - "5678:5678"
 ```
But again, its better to just use `example.com/api`.
