### ISSUE TITLE
Nginx reverse proxy: "Connection refused"

### ISSUE THREAD

**Issue by anoduck** [rr-/szurubooru#461]
If I browse straight to szurubouru, then I can connect, and the world is beautiful.
If I try to browse via nginx, I am recieving a 502 `111:Connection refused` error, and life doesn't make much sense.

Below is my current nginx configuration specific to forwarding to szuru:

```nginx
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header HOST $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Script-Name /szuru;
        
        proxy_pass http://client:8080;
        proxy_redirect off;
        proxy_cache STATIC;
        proxy_cache_valid 200 1d;
        proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
    
        error_page 500 501 502 504 505 506 507 508 509 510 511 @err;
      }

      location @err {
        return 500 "Something went wrong, please try again later.";
        default_type text/plain;
      }
}
```

Regardless of using the service name or the internal ip, the result is the same. Furthermore, the service name is resolved correctly to the internal IP. It is simply refusing NGINX the connection. 

```shell
2022/02/04 12:11:19 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.x.x.x, server: , request: "GET / HTTP/1.1", upstream: "http://172.25.x.x:8080/", host: "192.x.x.x"
nginxbox    | 192.x.x.x - - [04/Feb/2022:12:11:19 +0000] "GET / HTTP/1.1" 502 90 "-" "Mozilla/0.0 (X11; amd64; rv:00.0) Gecko/20100000 Firefox"
```

Is there something I am missing? Or is there a variable I need to set for Szuru?

**Comment by anoduck** [comment]
This is the third reverse proxy for a dockerized container I have configured in the last 24 hours. The other two worked without a problem, but with this one szurubouru is refusing connections. So I know my proxy configuration is correct, and all the variable for szurubouru appear to be correctly set.

Regardless, I stripped my nginx configuration to the bare minimum required flags, and this got me to the dreaded 502 bad gateway error.

```nginx
worker_processes     auto;
worker_rlimit_nofile 65535;

events {
    multi_accept       on;
    worker_connections 65535;
}

http {
    charset                utf-8;
    sendfile               on;
    tcp_nopush             on;
    tcp_nodelay            on;
    server_tokens          off;
    log_not_found          off;
    types_hash_max_size    2048;
    types_hash_bucket_size 64;
    client_max_body_size   65M;
    server_names_hash_bucket_size 128;

    # MIME
    include                mime.types;
    default_type           application/octet-stream;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    gzip  on;

    # Setup Caching
    proxy_cache_path /var/lib/nginx/cache levels=1:2 keys_zone=STATIC:10m inactive=24h max_size=1g;

    upstream szuru {
      server 172.xx.xx.2:8080;
    }

    server {
      listen 80 default_server;
      
      # Setting up logging
      access_log /var/log/nginx/szuru-access.log;
      error_log /var/log/nginx/szuru-error.log info;
    
      location ~ ^/api/(.*)$ {
        if ($request_uri ~* "/api/(.*)") { # preserve PATH_INFO as-is
            proxy_pass http://szserver:6666/$1;
         }
      }

      location = / {
        proxy_pass http://szuru;
        proxy_redirect off;
        proxy_cache STATIC;
        proxy_cache_valid 200 1d;
        proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
      }
    }
}
```
I read a now closed issue experienced by another user, which suggested establishing two different locations within the nginx configuration. One to proxy client and another to proxy the server. This made absolutely no difference, because as you can see the error occurs when nginx attempts to connect to the client on the client's port. 
```sh
2022/02/05 06:44:08 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.xxx.xx.xx, server: , request: "GET / HTTP/1.1", upstream: "http://172.xx.x.xx:8080/", host: "192.xxx.xx.xx"
2022/02/05 06:44:09 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.xxx.xx.xx, server: , request: "GET / HTTP/1.1", upstream: "http://172.xx.x.xx:8080/", host: "192.xxx.xx.xx"
```
Just for reference, I did attempt to set the url for port designation in the `.env` file, which did not resolve the issue.

Below is my docker-compose file. It appears to all be in order. I took the liberty to update the version number, since no conflicts were found that would prevent this.

```yaml
version: '3'

services:
# szserver -----------------------------------------------
  szserver:
    image: szurubooru/server:latest
    depends_on:
      - db
    environment:
      ## These should be the names of the dependent containers listed below,
      ## or FQDNs/IP addresses if these services are running outside of Docker
      POSTGRES_HOST: '172.xx.xx.4'
      ## Credentials for database:
      POSTGRES_USER: 'szuru'
      POSTGRES_PASSWORD: 'szuru'
      ## Commented Values are Default:
      #POSTGRES_DB: defaults to same as POSTGRES_USER
      POSTGRES_DB: 'szuru'
      LOG_SQL: 1
    volumes:
      - type: bind
        source: $PWD/szuru_data
        target: /data
      - type: bind
        source: ./server/config.yaml
        target: /opt/app/config.yaml
    ports:
      - "6666:6666"
    networks:
      net:
        aliases:
          - szserver
        ipv4_address: 172.xx.xx.3
# szclient ------------------------------------------------
  szclient:
    image: szurubooru/client
    depends_on:
      - szserver
    environment:
      BACKEND_HOST: '172.xx.xx.3'
      BASE_URL: '/'
    volumes:
      - type: bind
        source: $PWD/szuru_data
        target: /data
    ports:
      - "8080:80"
    expose:
      - "8080"
    networks:
      net:
        aliases:
          - szclient
        ipv4_address: 172.xx.xx.2
# Postgres ------------------------------------------------------
  db:
    image: postgres:11-alpine
    container_name: postbox
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'szuru'
      POSTGRES_PASSWORD: 'szuru'
      POSTGRES_DB: 'szuru'
    volumes:
      - type: bind
        source: $PWD/db
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    shm_size: 256MB
    networks:
       net:
        aliases:
          - db
        ipv4_address: 172.xx.xx.4
# NGINX ---------------------------------------------------------- 
  nginx:
    image: nginx:alpine
    container_name: nginxbox
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports: 
      - '80:80'
    expose:
      - '80'
    volumes:
      - type: bind
        source: $PWD/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: volume
        source: nginx-data
        target: /var/lib/nginx/cache
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      net:
        aliases:
          - nginx
        ipv4_address: 172.xx.xx.7
# Network -------------------------
networks:
  chan_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.xx.xx.0/24
          gateway: 172.xx.xx.1
# Volumes ---------------------------
volumes:
  nginx-data:
```
And here is my `.env` file, which little has been changed from the default.
```env
# Database credentials
POSTGRES_USER=szuru
POSTGRES_PASSWORD=szuru

# This shows up on the homescreen, indicating build information
BUILD_INFO=latest

# Port to expose HTTP service
# Set to 127.0.0.1:8080 if you wish to reverse-proxy the docker's port,
# otherwise the port specified here will be publicly accessible
PORT=8080

# URL base to run szurubooru under
# See "Additional Features" section in INSTALL.md
BASE_URL=/

# Directory to store image data
MOUNT_DATA=/var/local/szurubooru/data

# Directory to store database files
MOUNT_SQL=/var/local/szurubooru/sql
```
Here is a setup script to create the directories used, just for the heck of it. User needs to correctly set variable for their own system.
```shell
#!/usr/bin/env sh

mkdir -p szuru_data
mkdir -p db
echo 'directories ready'
```
With everything that I have included above, any Linux user should be able to successfully launch their own instance of szurubouru, and then test if the experienced error is reproducible.

At this point, I am all out of suggestions. There is no reason why nginx should not be able to connect to szurubouru.

**Comment by TiredSysOp** [comment]
># Port to expose HTTP service
># Set to 127.0.0.1:8080 if you wish >to reverse-proxy the docker's port,
># otherwise the port specified here will be publicly accessible
>PORT=8080

Smells like the issue is here. I'm aware you've fiddled with this
setting but try setting it to the loopback IP or a local one.

**Comment by anoduck** [comment]
Both `PORT=127.0.0.1:8080` & `PORT=127.xx.xx.x:8080`in `.env` failed to resolve the issue, currently it is set to `127.0.0.1:8080`. 

I also changed what port nginx listened on from 80 to 8000, hoping that the issue was merely nginx conflicting with the client's internal port, but this did not work as well.

After searching issues with 'docker network' I came up with several issues, unfortunately #301 is the only issue that came close, but it was not helpful.

I am just baffled with how nginx and its configuration work with two other containers hosting similar image board software, yet fail for szurubouru? I cannot see why?

**Comment by anoduck** [comment]
So, I removed all the networking configuration from `docker-compose.yml`, stripped that file down to a bare minimal configuration, hoping that this would allow docker to do it's thing, and no dice. I even went with using the nginx-proxy docker image over the standard nginx image, to allow as much automated configuration as possible. This didn't change a thing, szuru is simply refusing connections from nginx.

**Comment by neobooru** [comment]
The `ports: ...` configuration spec is `HOST:CONTAINER`. The issue is that you are trying to connect to the client at port `8080`, however this port `8080` only exists on the host. The container itself uses port 80 and this is also the port that you need to connect to within other containers in the same network. I don't exactly know what `expose` does, but you almost never need it.

In your case it is enough to change your `nginx.conf` to something like this:
```nginx
# Remove the :8080 part
proxy_pass http://172.20.20.2;
```

If you want to connect to the service name instead of an IP address then you have to make your nginx container depend on the szclient container.
```yml
nginx:
  image: nginx:alpine
  container_name: nginxbox
  depends_on:
    - szclient
  # etc ...
```

Then you can do something like this:
```nginx
proxy_pass http://szclient;
# alternatively, this also works for upstream
upstream client {
  server szclient;
}
```

That said, I feel like you are making things overly complicated for yourself. I believe (but am not entirely sure) that docker-compose creates a closed network for all the service in one docker-compose.yml file. As such, it is not needed to create a new network to separate it from the rest of your network/containers/host. It should be possible to just add your nginx container to the default szurubooru docker-compose.yml and change your settings there.

**Comment by sgsunder** [comment]
Agree with neobooru. I think the critical change is here:

```nginx
upstream szuru {
    server 172.xx.xx.2:8080;
}
```

should instead be:
```nginx
upstream szuru {
    server szclient:80;
}
```

1) You should refer to other containers by the hostname, not the IP address, because the container's IP address is dynamic and will not always work if you hardcode the IP address.
2) The `szclient` has its service on port 80, not 8080. The cause of confusion is that in your compose file, you have chosen to map port 8080 on the host machine to port 80 of the `szclient` container.

**Comment by anoduck** [comment]
That is sensical, but it was my understanding that each docker container is isolated from other containers. In which case, port 80 would only be available from within the szuru container and would not be available for other containers to connect to. The other containers would have to access the application running within the container from the translated port.

**Comment by anoduck** [comment]
Issue is over 2 months old, and was mitigated by another means. Closing out...

**Comment by TangentFoxy** [comment]
> and was mitigated by another means

@anoduck I'd really appreciate knowing what that is. I'm running into issues again, and can't figure out how things have gone wrong.

**Comment by anoduck** [comment]
@TangentFoxy I do not know what I was referring to, as it was three years ago, and frankly I do not even know why I was looking at a Chan for at that time. Which, leads me to believe I abandoned the effort altogether, being so pressed for time. 

503 errors are a bitch and a half to troubleshoot, but basically your wires are getting crossed somewhere. Not everyone does it, but I recommend you give defining your containerized network a try in your `docker-compose.yml` file, if you already haven't. Furthermore, enabling logging will also provide great help.

In general, my `docker-compose.yaml` files are much more robust than what most users create. I have attached the 'tour de force' of `docker-compose.yaml` files. It is not for szuruboru, so it might not be much help, but it does provide an example of how to precisely pin down your `docker-compose` configuration.

I apologize if this is no help. 

```yaml
#! vim: set filetype=yaml:

---
version: "3.9"

services:
  client:
    container_name: tahoe-client
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tahoe-client:alpha
    environment:
      TAHOE_ROLE: 'client'
    entrypoint: /root/tahoe-lafs/venv/bin/tahoe
    command: ["run", "/root/.tahoe-client"]
    depends_on:
      - introducer
      - server
    volumes:
      - "./repo:/root/tahoe-lafs"
      - "./client:/root/.tahoe-client"
      - "./introducer/private:/root/.tahoe-introducer/private"
    ports:
      - 3456:3456
    expose:
      - 3456
    networks:
      tahoe:
        aliases:
          - tahoe-client
        ipv4_address: 172.25.0.2
    restart: unless-stopped

  server:
    container_name: tahoe-server
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tahoe-server:alpha
    environment:
      TAHOE_ROLE: 'server'
    entrypoint: /root/tahoe-lafs/venv/bin/tahoe
    command: ["run", "/root/.tahoe-server"]
    depends_on:
      - introducer
      - tor
      - vanguards
    volumes:
      - "./repo:/root/tahoe-lafs"
      - "./server:/root/.tahoe-server"
      - "./introducer/private:/root/.tahoe-introducer/private"
    ports:
      - 3457:3457
    networks:
     tahoe:
        aliases:
          - tahoe-server
        ipv4_address: 172.25.0.3
    restart: unless-stopped
  
  introducer:
    container_name: tahoe-introducer
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tahoe-introducer:alpha
    environment:
      TAHOE_ROLE: 'introducer'
    entrypoint: /root/tahoe-lafs/venv/bin/tahoe
    command: ["run", "/root/.tahoe-introducer"]
    depends_on:
      - tor
      - vanguards
    volumes:
      - "./repo:/root/tahoe-lafs"
      - "./introducer:/root/.tahoe-introducer"
    networks:
      tahoe:
        aliases:
          - tahoe-introducer
        ipv4_address: 172.25.0.4
    ports:
      - 3458:3458
  
  tor:
    image: goldy/tor-hidden-service:latest
    environment:
      TOR_CONTROL_PORT: 172.25.0.5
      TOR_CONTROL_PASSWORD: PASSWORD
      VANGUARDS_EXTRA_OPTIONS: |
        [GLOBAL]
        enable_cbtverify = True

      TAHOE_TOR_SERVICE_HOSTS: 3456:tahoe-client:3456,3457:tahoe-server:3457,3458:tahoe-introducer:3458
      TAHOE_TOR_SERVICE_PORTS: 3456:3456,3457:3457,3458:3458
      TAHOE_TOR_SERVICE_VERSION: '3'
      TAHOE_TOR_SERVICE_KEY: |
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    volumes:
      - "tor-keys:/var/lib/tor/hidden_service/"
      - "tor-data:/run/tor/data"
    secrets:
      - source: tahoe-client
        target: tahoe-client
      - source: tahoe-server
        target: tahoe-server
      - source: tahoe-introducer
        target: tahoe-introducer
    networks:
      tahoe:
        aliases:
          - tor
        ipv4_address: 172.25.0.5
      tor:
        aliases:
          - tor-control
        ipv4_address: 172.25.1.5
    ports:
      - 9050:9050

  vanguards:
    depends_on:
      - tor
    image: goldy/tor-hidden-service:latest
    command: vanguards
    environment:
      TOR_CONTROL_PORT: tor
      TOR_CONTROL_PASSWORD: password
    volumes:
      - "tor-data:/run/tor/data"
    networks:
      tor:
        aliases:
          - vanguards
        ipv4_address: 172.25.1.7

  i2p:
    image: divax/i2p:latest
    container_name: i2box
    environment:
      ENABLE_HTTPPROXY: 1
      ENABLE_SOCKSPROXY: 1
      ENABLE_TUNNELS: 1
      BANDWIDTH: P
    volumes:
      - "./i2p/conf:./conf"
      - "./i2p/network:./network"
    ports:
      - 7070:7070
      - 4444:4444
      - 4544:4544
    networks:
      tahoe:
        aliases:
          - i2p
        ipv4_address: 172.25.0.6

volumes:
  tor-keys:
    driver: local
  tor-data:
    driver: local

secrets:
  tahoe-client:
    file: ./private_key_bar_v3
  tahoe-server:
    file: ./private_key_bar_v3
  tahoe-introducer:
    file: ./private_key_bar_v3

networks:
  tahoe:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1
  tor:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.25.1.0/24
          gateway: 172.25.1.1

```
