### ISSUE TITLE
How would i be able to change the text on specific pages & Importing from old site

### ISSUE THREAD

**Issue by Pikachubolk** [rr-/szurubooru#474]
Hi, I would like to change the text on the TOS page and change it up a little I've tried doing it by changing things in /szuru/client/Html/help_tos.tpl but it doesn't change anything

I've tried pulling it again restarting it 

I hope someone could help me with this, thanks.

**Comment by neobooru** [comment]
The easiest way to do this would be to edit your docker-compose.yml file like this.
```yml
# Under client, replace the "image: ..." line with "build: ./client"
# So, change this
#  client:
#    image: szurubooru/client:latest
# To this
  client:
    build: ./client
```

After this you should be able to just `docker-compose up` (or `docker-compose up -d`) to automatically build the client and start both the server and the client.
