### ISSUE TITLE
Can't edit head of main site

### ISSUE THREAD

**Issue by Hecking-Heck** [rr-/szurubooru#484]
I have looked everywhere I can think of and I am very new to doing all this sort of stuff but I am unable to edit the header of the main page. I have tried editing the home.tpl and index.htm files but nothing changes.

**Comment by neobooru** [comment]
I assume you are using the docker setup? By default that uses the prebuilt images, which means that local changes will be ignored.
To keep your local changes you need to build the image yourself. The easiest way to do this is to change the client service inside `docker-compose.yml`
```yml
services:
  # Don't touch 'server' etc

  client:
    # Comment out or delete the next line
    #image: szurubooru/client:latest
    # Add this line below
    build: ./client
    # Don't change the rest of the file
    depends_on:
        .....
```
It should look something like [this file](https://github.com/neobooru/szurubooru/blob/8b344ab8c163c6029bc5dbd7932125c8586666c3/docker-compose.yml). Though in that file also the server service has been changed, which you don't need to.

After this run the following two commands:
```sh
docker-compose build
docker-compose up -d
```

If the first command gives an error like `ERROR: Service 'server' failed to build: failed to parse platform : ""...` then run the following command and try again.
```sh
export DOCKER_BUILDKIT=1; export COMPOSE_DOCKER_CLI_BUILD=1
```
