### ISSUE TITLE
Make szurubooru autostart on fail

### ISSUE THREAD

**Issue by viasux** [rr-/szurubooru#502]
I do not appear to be able to run the container with "docker run szurubooru --restart unless-stopped", so how would I set it up to autostart unless manually stopped?

**Comment by FlipperLP** [comment]
Please share the error, that you get when running that command.

**Comment by viasux** [comment]
```
docker run szurubooru --restart unless-stopped
Unable to find image 'szurubooru:latest' locally
docker: Error response from daemon: pull access denied for szurubooru, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by viasux** [comment]
> Is there a reason, why you are not using the docker-compose file?. Because szurubooru has multiple images. You are currently trying to pull an image that doesn't exist with that name. But there is `szurubooru/server` and `szurubooru/client`. But again, because this also sets up a database and variables to encourage you to use the docker-compose file.

I believe that I am using the compose file, as I followed the installation directions.. I just have to `docker compose up -d` every single time

**Comment by FlipperLP** [comment]
Have you made sure, that you have a `docker-compose.yml` file?
And what happens, when you run the command then?

**Comment by viasux** [comment]
> Have you made sure, that you have a `docker-compose.yml` file? And what happens, when you run the command then?

Yes, a docker-compose.yml file is present in the directory that I run docker compose up -d in.

**Comment by FlipperLP** [comment]
can you try running
docker-compose up - d

so with a dash between docker and compose?

**Comment by viasux** [comment]
> can you try running docker-compose up - d
> 
> so with a dash between docker and compose?

gave me this error:
`ERROR: No such service: -`

**Comment by FlipperLP** [comment]
my bad. keyboard put a space there.. 

docker-compose up -d

**Comment by viasux** [comment]
> docker-compose up -d

oh my bad I think thats what I was doing initially, i just typed it without the dash by accident. I just did it that way to make sure though and it still doesn't start after restarting my virtual server.

**Comment by FlipperLP** [comment]
how does your docker-compose file look like? and what is the output from that?

**Comment by viasux** [comment]
docker-compose.yml:

```
## Example Docker Compose configuration
##
## Use this as a template to set up docker-compose, or as guide to set up other
## orchestration services
version: '2'

services:

  server:
    image: szurubooru/server:latest
    depends_on:
      - sql
    environment:
      ## These should be the names of the dependent containers listed below,
      ## or FQDNs/IP addresses if these services are running outside of Docker
      POSTGRES_HOST: sql
      ## Credentials for database:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      ## Commented Values are Default:
      #POSTGRES_DB: defaults to same as POSTGRES_USER
      #POSTGRES_PORT: 5432
      #LOG_SQL: 0 (1 for verbose SQL logs)
      THREADS:
    volumes:
      - "${MOUNT_DATA}:/data"
      - "./server/config.yaml:/opt/app/config.yaml"

  client:
    image: szurubooru/client:latest
    depends_on:
      - server
    environment:
      BACKEND_HOST: server
      BASE_URL:
    volumes:
      - "${MOUNT_DATA}:/data:ro"
    ports:
      - "${PORT}:80"

  sql:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - "${MOUNT_SQL}:/var/lib/postgresql/data"
```

output (in this case szurubooru is already running but it basically just says it started the services when i run it and its not running, i can get the exact output if needed):

```
docker-compose up -d
szuru_sql_1 is up-to-date
szuru_server_1 is up-to-date
szuru_client_1 is up-to-date
```
