### ISSUE TITLE
question: how to migrate booru from one ARM64 device to another?

### ISSUE THREAD

**Issue by urcades** [rr-/szurubooru#690]
I'm planning on moving a booru from an older raspberry pi 3+ to a raspberry pi 5. 

Do I need to perform anything special to move the booru from one device to another? Is there anything in particular I'm copying over to the new machine?

**Comment by urcades** [comment]
@nosyrbllewe gotcha, that makes sense! One last (potentially dumb) question along these lines: Does the docker yaml at the root of the repo indicate where these volumes live? I was browsing around my filesystem to try and fine the volumes they point to but couldn’t seem to find anything obviously indicative of my booru’s db.. pretty sure I kept the setup default and didn’t customize any of the paths or anything

**Comment by TiredSysOp** [comment]
https://github.com/rr-/szurubooru/blob/master/doc/example.env

**Comment by wanhuz** [comment]
Just want to add my experience here, I couldn't figure out easy way to migrate from ARMv7 to ARM64. 
I end up just using armv7 postgres image in my docker compose:

```
  sql:
    image: arm32v7/postgres:13-alpine # my version is 13
    restart: on-failure
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: abc
    ports:
      - "9099:5432"
    volumes:
      - "${MOUNT_SQL}:/var/lib/postgresql/data"
```
